const mongoose = require('mongoose');

const codingProfileSchema = new mongoose.Schema({
    platform:{
        type:String,
        required:true
    },
    handle:{
        type:String,
        required:true
    },
    profileUrl:{
        type:String,
    },
    avatar:{
        type:String,
        default:""
    },
    titlePhoto:{
        type:String,
        default:""
    },
    firstName:{
        type:String,
        default:""
    },
    lastName:{
        type:String,
        default:""
    },
    country:{
        type:String,
        default:""
    },
    city:{
        type:String,
        default:""
    },
    organization:{
        type:String,
        default:""
    },
    contribution:{
        type:Number,
        default:0
    },
    friendOfCount:{
        type:Number,
        default:0
    },
    registrationTimeSeconds:{
        type:Number,
        default:0
    },
    lastOnlineTimeSeconds:{
        type:Number,
        default:0
    },
    rating:{
        type:Number,
        default:0
    },
    maxRating:{
        type:Number,
        default:0
    },
    rank:{
        type:String,
        default:""
    },
    maxRank:{
        type:String,
        default:""
    },
    rankBadge:{
        label:{
            type:String,
            default:"unrated"
        },
        tier:{
            type:String,
            default:"unrated"
        },
        color:{
            type:String,
            default:"#6b7280"
        }
    },
    solvedCount:{
        type:Number,
        default:0
    },
    attemptedCount:{
        type:Number,
        default:0
    },
    submissionsCount:{
        type:Number,
        default:0
    },
    contestsCount:{
        type:Number,
        default:0
    },
    stats:{
        type:mongoose.Schema.Types.Mixed,
        default:{}
    },
    rawData:{
        type:Object,
        default:{}
    },
},{timestamps:true});

codingProfileSchema.index({ platform: 1, handle: 1 }, { unique: true });

const CodingProfile = mongoose.model('CodingProfile', codingProfileSchema);
module.exports = CodingProfile;
